### ISSUE TITLE
Checksum failure when decoding transport blocks

### ISSUE THREAD

**Issue by jullianzz** [FabianEckermann/cv2x-traffic-generator#1]
## Issue Description 
- Packets are failing the CRC checksum (`srslte_bit_diff`) in the `srslte_pssch_decode` function in `pssch_ue`. This causes `num_decoded_tb` to always equal 0 (even when `num_decoded_sci` is non-zero), or takes a very long time before a packet passes `srslte_pssch_decode`.

## Setup Details
We have tried 2 different synchronization setups to fix this issue. We are using two NI 2901 USRPs.
1. Synchronization with 2 Keysight waveform generators. Both USRPs are connected to a signal generator at 10MHz and another at 1 Hz. 
2. Synchronization with GPSDO using OctoClock clock distribution module 

## Expected Behavior
- `num_decoded_tb` to be a non-zero value during transmission of C-V2X packets. 

## Steps to reproduce the problem
- Add `ERROR("Checksum error")` error printing statements within the CRC checksum in `pssch.ue/srslte_pssch_decode`, i.e.:
1.  Change # 1
```
  if (srslte_bit_diff(q->cb_crc_temp, &q->c_r[(K_r - L)], L) != 0) {
        ERROR("Checksum error");
        return SRSLTE_ERROR;
  }
```
2. Change # 2
```
  if (srslte_bit_diff(q->tb_crc_temp, &q->b[(B - SRSLTE_PSSCH_CRC_LEN)], SRSLTE_PSSCH_CRC_LEN) != 0) {
    ERROR("Checksum error");
    return SRSLTE_ERROR;
  }
```
- For waveform generator synchronization: Run `./pssch_ue` and `./cv2x_traffic_generator -d UHD -a clock=external -n 5 -l 10 -s 0` on separate USRPs
- For OctoClock synchronization: Run `./pssch_ue` and `./cv2x_traffic_generator -d UHD -a clock=gpsdo` on separate USRPs

**Comment by SamKrasnoff** [comment]
Hi Julia and Fabian,
Allow me to correct you Julia, we actually used following commands with OctoClock GPSDO distribution module. We don't have internal GPSDO so in both ways we tried (OctoClock or waveform generator) clock and time setting should be external.
```
./build/cv2x_traffic_generator/cv2x_traffic_generator -d 31EEB59 -a clock=external,time=external -i sf_config.csv
writing logfile: /home/dragon/v2x_tg_logfiles/v2x_tg_2022_4_20-11_23_21.csv
Reading input file sf_config.csv
Opening RF device...
[INFO] [UHD] linux; GNU C++ version 9.2.1 20200304; Boost_107100; UHD_3.15.0.0-2build5
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=1, args: time=external,master_clock_rate=23.04e6
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
Set TX freq: 2450.000000 MHz
Set TX gain: 80.0 dB
Setting sampling rate 11.52 MHz
creating signal buffers...
start time: 2.206468
```

```
./build/pssch_ue/pssch_ue -d 31EEB5E -a "time=external,clock=external" -g 80
Opening RF device...
[INFO] [UHD] linux; GNU C++ version 9.2.1 20200304; Boost_107100; UHD_3.15.0.0-2build5
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=1, args: time=external,master_clock_rate=23.04e6
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
Set RX freq: 2450.000000 MHz
Set RX gain: 80.0 dB
Setting sampling rate 11.52 MHz
Using a SF len of 11520 samples
SCI1: riv=5, mcs=20, priority=6, res_rsrv=2, t_gap=5, rtx=0, txformat=1
SCI1: riv=8, mcs=18, priority=1, res_rsrv=12, t_gap=14, rtx=1, txformat=1
^CSIGINT received. Exiting...
num_decoded_sci=2 num_decoded_tb=0
```

We get the uhd rf device name with: 
```
uhd_find_devices 
[INFO] [UHD] linux; GNU C++ version 9.2.1 20200304; Boost_107100; UHD_3.15.0.0-2build5
--------------------------------------------------
-- UHD Device 0
--------------------------------------------------
Device Address:
    serial: 31EEB59
    name: NI2901
    product: B210
    type: b200


--------------------------------------------------
-- UHD Device 1
--------------------------------------------------
Device Address:
    serial: 31EEB5E
    name: NI2901
    product: B210
    type: b200
```

We tried different TX/RX gains, over-the-air with correct antennas, and over-the-wire scenario with at least 35dBm attenuation between TX and RX. In all cases we get num_decoded_tb to be zero. In fact, even if cv2x-traffic-generator is not running, the pssch_ue output is the same, num_decoded_sci=xx, num_decoded_tb=0.

Do you have any hints or ideas what might be wrong?
Are we using the cv2x-traffic-generator and pssch_ue apps in a correct way?
Or do you think something with our radios is wrong?
It would potentially help if you could post a shell output of your working setup.

Best,
Sam

**Comment by FabianEckermann** [comment]
Hi Julia and Sam,
I don't have SDRs at hand to reproduce this error and only tested this with GPSDOs added to the SDRs. Your shell output looks good, so it might be a problem with the Octoclock or waveform generator.
